version: '3.1'

services:

  app:
    build: .
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: "npm run dev"
    depends_on:
      - db
      - adminer
  
  app-test:
    build: .
    restart: always
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: "npm run test"
    depends_on:
      - db
  
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: "app-user"
      POSTGRES_PASSWORD: "app-password"
      POSTGRES_DB: "appdb"
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db