version: '3.1'

services:

  app:
    build: .
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: "npm run dev"
    depends_on:
      - mongo
  
  app-test:
    build: .
    restart: always
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: "npm run test"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: app
    volumes:
      - ./docker/mongo/init.js:/docker-entrypoint-initdb.d/init.js

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - mongo